### ISSUE TITLE
Taiko support

### ISSUE THREAD

**Issue by akira-okumura** [PicoQuant/PQLaserDrv#1]
Does it support Taiko PDL? It looks that the library in Demo is written only for Sepia PDL. I am wondering if you could provide a Python demo for Taiko.

**Comment by snizzleorg** [comment]
This currently does not support Taiko PDL. Taiko PDL also comes with an API: https://www.picoquant.com/dl_manuals/Taiko_API_Manual.pdf but we currently do not have any demos on how to use it on GitHub. However, after installing the Taiko software and driver you can find API demos under `C:\ProgramData\Taiko PDL M1\API\Demos`. Currently API demos are available for Python, C, LabView and Matlab.

**Comment by akira-okumura** [comment]
Thank you. I found the code. Do I always need to use the Windows DLL to control a Taiko PDL? Is there any open document that describes how to communicate with the PDL with more standard protocol like serial or USB?

**Comment by snizzleorg** [comment]
Yes you will need the Windows DLL. Unfortunately we currently do not offer a more standard protocol for communicating with the Taiko.
